#pragma once
#include "native.h"
#include "hcdef.h"

typedef ULONG HIGHCALL_STATUS;

#define HIGHCALL_ADVANCE(Status)				((HIGHCALL_STATUS)(Status) >= 0)
#define HIGHCALL_SUCCESS						((HIGHCALL_STATUS)0x00000000L)
#define HIGHCALL_FAILED							((HIGHCALL_STATUS)0xC0000001L)
#define HIGHCALL_OPENPROCESSTOKEN_UNDEFINED		((HIGHCALL_STATUS)0xC0000002L)
#define HIGHCALL_RTLGETVERSION_UNDEFINED		((HIGHCALL_STATUS)0xC0000003L)

extern BOOLEAN HcGlobalElevated;
extern ULONG HcGlobalWindowsVersion;

HIGHCALL_STATUS HCAPI HcInitialize();
